// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RecipeWebApp.Models;

namespace RecipeWebApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200726160545_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RecipeWebApp.Models.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AvrgRate");

                    b.Property<string>("Category");

                    b.Property<string>("Chef")
                        .IsRequired();

                    b.Property<string>("Culture");

                    b.Property<string>("Description");

                    b.Property<string>("Direction")
                        .IsRequired();

                    b.Property<DateTime>("EditDate");

                    b.Property<string>("Ingredient")
                        .IsRequired();

                    b.Property<string>("Nutrition");

                    b.Property<string>("PreparationTime")
                        .IsRequired();

                    b.Property<int>("Servings");

                    b.Property<string>("Title")
                        .IsRequired();

                    b.Property<string>("Yield");

                    b.HasKey("Id");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("RecipeWebApp.Models.Review", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<string>("Note");

                    b.Property<int>("Rate");

                    b.Property<int>("RecipeId");

                    b.Property<string>("Title");

                    b.Property<DateTime>("dateTime");

                    b.HasKey("ID");

                    b.ToTable("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
